### ISSUE TITLE
problem while running hrekt

### ISSUE THREAD

**Issue by sahadev0079** [ethicalhackingplayground/hrekt#2]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', /home/ubuntu/.cargo/git/checkouts/wappalyzer-1dd64d55c4039444/a2c1a8f/src/lib.rs:71:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sahadev0079** [comment]
hrekt --title
   
    __              __   __ 
   / /_  ________  / /__/ /_
  / __ \/ ___/ _ \/ //_/ __/
 / / / / /  /  __/ ,< / /_  
/_/ /_/_/   \___/_/|_|\__/  
                            
                v0.1.6
    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chrome launched, but didn't give us a WebSocket URL before we timed out', /home/ubuntu/.cargo/git/checkouts/wappalyzer-1dd64d55c4039444/a2c1a8f/src/lib.rs:71:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: wappalyzer::new_browser
   4: hrekt::main::{{closure}}
   5: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
   8: hrekt::main

**Comment by sumgr0** [comment]
Saw the project and when trying to resolve a small file with 10 hosts, its resulting in the same error message.
